version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    target-branch: 'next'
    groups:
      all-dependencies:
        patterns:
          - '*'
