type Manifest @embedded {
  # manifest id
  id: String!
  #
  title: String
  description: String
  nsfw: Boolean
  author: String
  image: String
  url: String
  depends: [String!]
  conflicts: [String!]
  media: MediaObject
  characters: CharacterObject
}

type MediaObject @embedded {
  conflicts: [String!]
  new: [DisaggregatedMedia!]
}

type CharacterObject @embedded {
  conflicts: [String!]
  new: [DisaggregatedCharacter!]
}

type DisaggregatedMedia @embedded {
  id: String!
  type: String!
  title: Alias!
  format: String
  description: String
  popularity: Int
  images: [Image!]
  externalLinks: [ExternalLink!]
  trailer: Trailer
  relations: [MediaRelation!]
  characters: [CharacterRelation!]
}

type DisaggregatedCharacter @embedded {
  id: String!
  name: Alias!
  description: String
  popularity: Int
  gender: String
  age: String
  images: [Image!]
  externalLinks: [ExternalLink!]
  media: [CharacterMediaRelation!]
}

type Alias @embedded {
  english: String
  romaji: String
  native: String
  alternative: [String!]
}

type Image @embedded {
  url: String!
  artist: ImageArtist
}

type ImageArtist @embedded {
  username: String
  url: String
}

type ExternalLink @embedded { 
  url: String!
  site: String!
}

type Trailer @embedded {
  id: String!
  site: String!
}

type MediaRelation @embedded {
  relation: String!
  mediaId: String!
}

type CharacterRelation @embedded {
  role: String!
  characterId: String!
}

type CharacterMediaRelation @embedded {
  role: String!
  mediaId: String!
}