type Response @embedded {
  ok: Boolean!
  error: String
  character: Character
  inventory: Inventory
  manifest: Manifest
}

type Verify @embedded {
  ok: Boolean!
  message: String
  errors: [String!]
}

type CharacterNode @embedded {
  character: Character
  anchor: String
}

type Query {
  #
  getGuildInstance(guildId: String!): Instance!
    @resolver(name: "get_guild_instance")

  #
  getUserInventory(userId: String!, guildId: String!): Inventory!
    @resolver(name: "get_user_inventory")
  
  #
  getUserStars(userId: String!, guildId: String!, stars: Int!, before: String, after: String): CharacterNode!
    @resolver(name: "get_user_stars")
  #
  getUserMedia(userId: String!, guildId: String!, mediaId: String!, before: String, after: String): CharacterNode!
    @resolver(name: "get_user_media")
  
  #
  findMedia(mediaId: String!, guildId: String!, before: String, after: String): CharacterNode
    @resolver(name: "find_media")

  #
  findCharacter(characterId: String!, guildId: String!): Character
    @resolver(name: "find_character")
  
  #
  verifyCharacters(charactersIds: [String!]!, guildId: String!, userId: String!): Verify!
    @resolver(name: "verify_characters")
}

type Mutation {
  #
  addVoteToUser(userId: String!, weekend: Boolean!): Response!
    @resolver(name: "add_vote_to_user")

  #
  addPackToInstance(userId: String!, guildId: String!, githubId: Int!, manifest: ManifestInput!): Response!
    @resolver(name: "add_pack_to_instance")
  
  #
  removePackFromInstance(guildId: String!, manifestId: String!): Response!
    @resolver(name: "remove_pack_from_instance")

  #
  addCharacterToInventory(
    userId: String!
    guildId: String!
    characterId: String!
    mediaId: String!
    rating: Int!
    pool: Int!
    popularityChance: Int!
    popularityGreater: Int!
    popularityLesser: Int
    roleChance: Int
    role: String
  ): Response! @resolver(name: "add_character_to_inventory")

  #
  setCharacterToParty(userId: String!, guildId: String!, characterId: String!, spot: Int): Response!
    @resolver(name: "set_character_to_party")
  #
  swapCharactersInParty(userId: String!, guildId: String!, a: Int!, b: Int!): Response!
    @resolver(name: "swap_characters_in_party")
  #
  removeCharacterFromParty(userId: String!, guildId: String!, spot: Int!): Response!
    @resolver(name: "remove_character_from_party")

  #
  giveCharacters(userId: String!, targetId: String!, guildId: String!, charactersIds: [String!]!): Response!
    @resolver(name: "give_characters")
  
  #
  tradeCharacters(
    userId: String!
    targetId: String!
    guildId: String!
    giveCharactersIds: [String!]!
    takeCharactersIds: [String!]!
  ): Response! @resolver(name: "trade_characters")

  #
  customizeCharacter(
    userId: String!
    guildId: String!
    characterId: String!
    nickname: String
    image: String
  ): Response! @resolver(name: "customize_character")
}
